export const FETCHING_CATALOG = 'FETCHING_CATALOG';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_ERROR = 'FETCH_CATALOG_ERROR';
export const FETCH_PHONE_DETAILS = 'FETCH_PHONE_DETAILS';
